spring.application.name=employeeleavemanagementsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/elms
spring.datasource.username=postgres
spring.datasource.password=roshan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.security.user.name=admin
spring.security.user.password=admin123


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roshansonje1@gmail.com
spring.mail.password=ixuvnjtoodukrauz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true